[tool.poetry]
name = "pricing-python"
version = "0.1.0"
description = ""
authors = ["matt"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
quantlib = "^1.35"
numpy = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
